//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCrystalDownloadHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCrystalDownloadHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRRuntime_32bit_13_0_30.msi.
        /// </summary>
        internal static string crfname32 {
            get {
                return ResourceManager.GetString("crfname32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRRuntime_64bit_13_0_30.msi.
        /// </summary>
        internal static string crfname64 {
            get {
                return ResourceManager.GetString("crfname64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 130303805.
        /// </summary>
        internal static string crminversion {
            get {
                return ResourceManager.GetString("crminversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP Crystal Reports runtime engine for .NET Framework (32-bit).
        /// </summary>
        internal static string crname32 {
            get {
                return ResourceManager.GetString("crname32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP Crystal Reports runtime engine for .NET Framework (64-bit).
        /// </summary>
        internal static string crname64 {
            get {
                return ResourceManager.GetString("crname64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\SAP BusinessObjects\Crystal Reports for .NET Framework 4.0\Crystal Reports.
        /// </summary>
        internal static string crruntimeversion_registry_key {
            get {
                return ResourceManager.GetString("crruntimeversion_registry_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://origin.softwaredownloads.sap.com/public/file/0020000000195592021.
        /// </summary>
        internal static string cruri32 {
            get {
                return ResourceManager.GetString("cruri32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://origin.softwaredownloads.sap.com/public/file/0020000000195602021.
        /// </summary>
        internal static string cruri64 {
            get {
                return ResourceManager.GetString("cruri64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall.
        /// </summary>
        internal static string uninstall_registry_key {
            get {
                return ResourceManager.GetString("uninstall_registry_key", resourceCulture);
            }
        }
    }
}
